apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-winstead-io
  namespace: cert-manager
spec:
  secretName: wildcard-winstead-io
  dnsNames:
    - "*.winstead.io"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
