apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - namespace.yaml

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  version: 1.13.1
  # TODO:
  # valuesFile: values.yaml
