apiVersion: v1
kind: Secret
metadata:
    name: argocd-sso
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.github.id: ENC[AES256_GCM,data:crVQpjm4gqUSCdDyvMl4CGxQSyU=,iv:lrAAFjjLD3pbyoqa8s/gntnNQdtjmOtIL7fANq2Eu5g=,tag:DfhrL/Kao1t5CQJ2yOqfFA==,type:str]
    dex.github.secret: ENC[AES256_GCM,data:sA9J1LNrE25yf5ESvEoYfvUCn87UbWWos0B8m22l5/WTdxH1tLtF6g==,iv:gV8jWTvE5XmfqQyHPxqoP/SJN7y3syrgRvNv8wkHTrM=,tag:NK/h8mx4IUxenR+8HFmJRA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:338208726210:key/5f27f89c-2f4e-49c9-9263-63596049bde5
          created_at: "2023-12-22T00:28:25Z"
          enc: AQICAHjgw/vIYU2CX5id4R5kz7lKeSSRLiACpC/t30YYpZazkAHMMXNcUtx/flkIiULB7awNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+waLkhkoMN/+TrM0AgEQgDvE+4O10L1wWzhLVqpqUmyzIYYq/6+6laL2rB7gPX0b8+C8RAuh2mkitP2ErxBNGheefrs9T2Qd2qVnkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T18:59:16Z"
    mac: ENC[AES256_GCM,data:UlStM4Xw+IkSBnhHW4OTtrlMzdgqYM9N3ZqYxthMyJkLqww78V97yCdZIsSzmfY/w0ZelIVYVUKLxbiENrkHq5EjwnYpmF5ZvtFaW50nNEMbEjOm4ycobS+zb+lrQWYRP/G4Szh7pqCZ0+PJvAcXtL5Uw14qn8jQNjjkbIAtUgo=,iv:cLVmUt56AWRAwp42vkk0Bkvqmc2QyTjtQA6iBnZFKpM=,tag:Ec/2I8FOiFcpvtGROmq77w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: aws-creds
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:U01qRVYKSM7/9RJAZ6sWvrhrNcg=,iv:wJDu9OYJAo612f2MXMppTj9BtFNFkQ5sf+33AG62J9E=,tag:5EdD6CPXQKgsrNestE1AGQ==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:W2xhcT7YwToZGyoWggh67bnTYPPYbkXvVG1+wAldopnX3c+ZbodvgA==,iv:so0KKftB5MV8OyexutIkEsVDEWaQiqbCNt7tyvhGIkI=,tag:FupoKkMMPZ4A7uOG8wkiZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:338208726210:key/5f27f89c-2f4e-49c9-9263-63596049bde5
          created_at: "2023-12-22T00:28:25Z"
          enc: AQICAHjgw/vIYU2CX5id4R5kz7lKeSSRLiACpC/t30YYpZazkAHMMXNcUtx/flkIiULB7awNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+waLkhkoMN/+TrM0AgEQgDvE+4O10L1wWzhLVqpqUmyzIYYq/6+6laL2rB7gPX0b8+C8RAuh2mkitP2ErxBNGheefrs9T2Qd2qVnkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T18:59:16Z"
    mac: ENC[AES256_GCM,data:UlStM4Xw+IkSBnhHW4OTtrlMzdgqYM9N3ZqYxthMyJkLqww78V97yCdZIsSzmfY/w0ZelIVYVUKLxbiENrkHq5EjwnYpmF5ZvtFaW50nNEMbEjOm4ycobS+zb+lrQWYRP/G4Szh7pqCZ0+PJvAcXtL5Uw14qn8jQNjjkbIAtUgo=,iv:cLVmUt56AWRAwp42vkk0Bkvqmc2QyTjtQA6iBnZFKpM=,tag:Ec/2I8FOiFcpvtGROmq77w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
