apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Replace all the orb.local domains with prd domains
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argocd.winstead.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: argocd.winstead.io
    target:
      kind: Ingress
      labelSelector: app.kubernetes.io/part-of=argocd
      annotationSelector: nginx.ingress.kubernetes.io/backend-protocol=HTTP
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: grpc.argocd.winstead.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: grpc.argocd.winstead.io
    target:
      kind: Ingress
      labelSelector: app.kubernetes.io/part-of=argocd
      annotationSelector: nginx.ingress.kubernetes.io/backend-protocol=GRPC
