apiVersion: v1
kind: Secret
metadata:
    name: argocd-sso
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.github.id: ENC[AES256_GCM,data:JJLJi5uIosWqoTIsFTEg7EEMPRQ=,iv:fw5WknXmp8q6cxlSPv7vTVNBhi7oPghG1uzJB48ERfU=,tag:eocWM1WQlKc3W2JTdBVbFA==,type:str]
    dex.github.secret: ENC[AES256_GCM,data:MKgeae8JwRC8a6K2KqiqRXdSklFfr9Ub1syEpfrJZiWi49LtK5PCfA==,iv:c/zjfcrPei7JEpWyuv2ADzsoSxnkGpD3J5ETwui/BRk=,tag:R5yPTSWjdUnUM2ZwF6voJw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:338208726210:key/5f27f89c-2f4e-49c9-9263-63596049bde5
          created_at: "2023-12-19T02:13:05Z"
          enc: AQICAHjgw/vIYU2CX5id4R5kz7lKeSSRLiACpC/t30YYpZazkAEJfVVr1xOO0E29lazghzKhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYs4QagmtmnvHvFojAgEQgDuPC71pU6c7PsoXMW5K0MBm5EINkOm3XYksi6/PVMtyGYVt0r6Q2y4lKuV9dPwGynB4xXfmSWNGpOKq0g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T19:03:26Z"
    mac: ENC[AES256_GCM,data:taycn16nnvgiWTfEjWnCBLBinivMRgHz1FpjqhnFa4ASkrcps0EoQq0C7eqvdxD6FNeqYuTCsXk+kLbY93n3lh1bhNtpSVHO4QWhrMWbcAolvErRkwxSouZU0LYjVetZBreiwnBzLirdxv4ILSqI8OO8YZaN8NqU8lXn6Jy4zKg=,iv:yOjUqKVON0qNKXSh0L6CHkPKuNANTy7X3Dk2rod0zkY=,tag:HB4etzJei57i7colZMgwuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
