apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform/02-ingress-nginx/overlays/prd
    repoURL: https://github.com/bmwinstead/home-argo
    targetRevision: main
