apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-orb-local
spec:
  secretName: wildcard-orb-local
  dnsNames:
    - "*.k8s.orb.local"
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
