apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base
  - certs.yaml

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  namespace: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: "4.9.0"
  valuesFile: values.yaml
